
version: 2

models:
  - name: Customer_details
    description: '{{ doc("Customer_details") }}'
    columns:
      - name: full_name
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: '{{ doc("stg_orders") }}'
    columns:
      - name: status
        description: "Status of the order shipment"
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    description: '{{ doc("stg_payments") }}'
    columns:
      - name: payment_method
        description: "Venue by how the payments are done"
        tests:
          - accepted_values:
              values:  ['coupon', 'bank_transfer', 'gift_card', 'credit_card'] 

sources:
  - name: snowflake_sample_datas
    description: 'A sample database'
    database : snowflake_sample_data
    schema : TPCDS_SF10TCL
    tables :
      - name : store_sales
        description : 'details about sales in the store'
  - name: artist_source
    description: 'An artist database'
    database : DEMO_DB
    schema : staging
    tables :
      - name : artist_data
        description : 'details about artist_data'
  
  - name: orders_source
    description: 'Source to keep track of orders table'
    database: DEMO_DB
    schema: public
    tables: 
      - name: order_details 
        description: 'Details about order made'
    
    
